---
- name: Stop EC2 Instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Stop EC2 instance
      ec2_instance:
        instance_ids: i-065e63dbdb17c1e96
        state: stopped
      register: ec2_result

    - name: Print EC2 stopping result
      debug:
        var: ec2_result

